# Generated by Django 2.1.2 on 2018-10-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lover_recorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上次登录时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='register_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='注册时间'),
        ),
    ]
